services:
  - type: web
    name: knights-tour-solver
    runtime: python
    buildCommand: ../../../build.sh
    startCommand: gunicorn main:app
    workingDir: src/api/venv
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production
